services:
  - type: web
    name: student-info-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
    region: oregon
    plan: free
